- name: Copy
  become: true
  copy:
    src: ./files/nginx/sites-available/isuride.conf
    dest: /etc/nginx/sites-available/isuride.conf
    mode: "0644"
    backup: true

- name: nginx is restarted
  become: true
  systemd:
    name: nginx
    state: restarted
